### ISSUE TITLE
How to use ?

### ISSUE THREAD

**Issue by anhmuonnoi** [emrcftci/CleanSwiftTemplate#2]
i am not understand use ?

**Comment by emrcftci** [comment]
You should just download the repo and double-click to `importTemplates` and then you will be able to use the template in your Xcode.

------------------------------
Installation
------------------------------
 - Download the repo
 - Double-click to `importTemplates`
 - Open your Xcode project
 - CMD + N (New File) > scroll down to see `Clean Swift Files` section, double-click on `Clean Files`
![Screen Shot 2020-04-02 at 11 34 31](https://user-images.githubusercontent.com/19268363/78227861-99c6fe00-74d6-11ea-8db8-451215032a71.png)

 - You should type your scene / feature name and click `Next`

This is how we can use file templates of Xcode.
I'll add some information about this in the README.
